name: Release

on:
  workflow_dispatch:

jobs:
  Release:
    name: "Release"
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    
    - name: Check for Duplicate Tags
      run: |
        if git rev-parse -q --verify "refs/tags/${{ github.ref }}" >/dev/null; then
          echo "Tag already exists. A version bump is required."
          exit 1
        fi
        
    - id: set_var
      run: |
        content=`cat ./manifest.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=packageJson::$content"
        
    - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
          
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.set_var.outputs.version }}"
          prerelease: false
          title: ${{ steps.set_var.outputs.version }}
          files: |
            buildOut/client.zip
            buildOut/server.zip
            buildOut/modlist.html
